/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas;

import com.mysql.cj.jdbc.ConnectionImpl;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ar_rr
 */
public class Productos extends javax.swing.JDialog {

    /**
     * Creates new form Productos
     */
    public Productos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         this.setTitle("Productos");
         this.setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
         this.pack();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 302, -1));

        jLabel1.setText("INTRODUCIR DATOS PARA AÑADIR REGISTRO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 22, -1, -1));

        jLabel2.setText("PRODUCTO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 53, -1, -1));

        jLabel3.setText("Nº UNIDADES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 130, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 127, 303, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 204, -1, -1));

        jLabel5.setText("PRECIO POR U.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 213, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 210, 303, -1));

        jButton1.setText("AÑADIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 250, 147, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID PRODUCTO", "NOMBRE", "CANTIDAD", "PRECIO (POR U.)", "ACCIONES"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 319, 1064, 209));

        jButton2.setText("ACTUALIZAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1004, 546, 125, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void conexion(){   
          
           String Base_Datos ="jdbc:mysql://localhost";
           String User = "root";
           String Contrasenna  ="12345";
           com.mysql.cj.jdbc.ConnectionImpl conexion;
           Statement prepst;
           
             String nombre = jTextField4.getText();
             int numerou = parseInt(jTextField1.getText());
             double precio = parseDouble(jTextField2.getText());
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }

    if((jTextField1.getText().length()==0 && jTextField2.getText().length()==0 && jTextField4.getText().length()== 0 ) || (jTextField4.getText().length()==0)){
            JOptionPane.showMessageDialog(null, "Rellene los campos");
        }
        else{
        try {
            conexion = (com.mysql.cj.jdbc.ConnectionImpl) java.sql.DriverManager.getConnection(Base_Datos, User, Contrasenna );
            prepst = (Statement) conexion.createStatement();
            prepst.executeUpdate("use tiendademusica;");
            String insercion = ("INSERT INTO productos (nombre, precio, unidades_disponibles) VALUES ('"+nombre+"', '"+precio+"', '"+numerou+"')");
            prepst.execute(insercion);
            prepst.close();
            conexion.close();
        } catch (java.sql.SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        } }}
/*
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            conexion();


    }//GEN-LAST:event_jButton1ActionPerformed
*/
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
           try{ 
    conexion();}
            catch (NumberFormatException ex) { // handling  exception
            JOptionPane.showMessageDialog(null, "Acción no permitida. Revise los valores de los campos.");
        }
    }        
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            datosdetabla(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          int columna;
        int fila;
        columna = jTable1.getColumnModel().getColumnIndexAtX(evt.getX());
        fila = evt.getY()/jTable1.getRowHeight();
        if(columna<=jTable1.getColumnCount() && columna >= 0 && fila <= jTable1.getRowCount() && fila >=0){
            
        Object obj = jTable1.getValueAt(fila, columna);
        if(obj instanceof JButton){
            ((JButton)obj).doClick();
             JButton bot = (JButton)obj;
             if(bot.getName().equals("Borrar")){
                 
                try {
                    eliminaregistro();
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
             }
             else{
                 try {
                    actualizaregistro();
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
             }
        }
        }
              
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Productos dialog = new Productos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
/*
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration                   
*/
  public  void datosdetabla(JTable jtable) throws java.sql.SQLException {
        String Base_Datos ="jdbc:mysql://localhost";
        String User = "root";
        String Contrasenna  ="12345";
        DefaultTableModel modelotabla = new DefaultTableModel(){
            //esto lo hacemos para que no se pueda editar lo dispuesto en la tabla haciendo doble click
       @Override
           public boolean isCellEditable(int row, int column){
    	 
              
               if (column == 1 || column == 2 || column ==3){
                   return true;
               }
                 return false;
           }};
        java.sql.ResultSet rs = null;
        String [] datostabla = new String [5];
         ConnectionImpl conexion = null;
         Statement prepst = null;
         String busqueda = ("SELECT * FROM productos");
        
        try {
            conexion = (com.mysql.cj.jdbc.ConnectionImpl) java.sql.DriverManager.getConnection(Base_Datos, User, Contrasenna );
             prepst = (Statement) conexion.createStatement();
            prepst.executeUpdate("use tiendademusica;");
            jTable1.setDefaultRenderer(Object.class, new imagenes());
            
            modelotabla.addColumn("ID PRODUCTOS");
            modelotabla.addColumn("NOMBRE");
            modelotabla.addColumn("PRECIO");
             modelotabla.addColumn("UNIDADES DISPONIBLES");
           modelotabla.addColumn("EDITAR");
           modelotabla.addColumn("BORRAR");
        
            
        
            rs = prepst.executeQuery(busqueda);
          
           
        } catch (java.sql.SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
   //     ArrayList<datos> arraydedatos = new arraydedatos(numero, nombre, apellidos, telefono);
       
           
        /*    try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
7        }*/

             java.sql.ResultSet trd = null;
        try {
            conexion = (com.mysql.cj.jdbc.ConnectionImpl) java.sql.DriverManager.getConnection(Base_Datos, User, Contrasenna );
            prepst = (Statement) conexion.createStatement();
            prepst.executeUpdate("use tiendademusica;");
            rs = prepst.executeQuery(busqueda);
            
        } catch (java.sql.SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    
   /*7 while (rs.next()) {
                numero = rs.getInt("id_productos");
                nombre = rs.getString("nombre");
                precio = parseDouble(rs.getString("precio"));
                numerou = parseInt(rs.getString("unidades_disponibles"));
        }
                
                
           
            }*/
        JButton editar = new JButton("Editar");
        
        
 
       JButton borrar = new JButton("Borrar");
       editar.setName("Editar");
        borrar.setName("Borrar");
       while(rs.next()){     
        for(int i=0; i<1; i++){ 
                Object f[] = new Object[6];
                f[0] = rs.getInt("id_productos");
                f[1] = rs.getString("nombre");
                f[2] = rs.getString("precio"); 
                f[3] = rs.getString("unidades_disponibles");
                f[4] = editar;
                f[5] = borrar;
                modelotabla.addRow(f);}
       }
   
    jTable1.setModel(modelotabla);
            prepst.close();
            conexion.close();
            rs.close();
        
     
  }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
    
   
    
    private void actualizaregistro() throws SQLException{
                String Base_Datos ="jdbc:mysql://localhost";
                String User = "root";
                String Contrasenna  ="12345";
                ConnectionImpl conexion = (com.mysql.cj.jdbc.ConnectionImpl) java.sql.DriverManager.getConnection(Base_Datos, User, Contrasenna );
                try{
                Statement actualizar = (Statement) conexion.createStatement();
                actualizar.executeUpdate("use tiendademusica");
                
                jTable1.isCellEditable(jTable1.getSelectedRow(),jTable1.getSelectedColumn());
                String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                String nombre = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
                int precio = Integer.parseInt((String) jTable1.getValueAt(jTable1.getSelectedRow(), 2));
                int unidades_disponibles = Integer.parseInt((String) jTable1.getValueAt(jTable1.getSelectedRow(), 3));
                String sentencia = "UPDATE productos SET nombre='"+nombre+"', precio='"+precio+"', unidades_disponibles='"+unidades_disponibles+"' WHERE id_productos='"+id+"';";
                actualizar.executeUpdate(sentencia);
                JOptionPane.showMessageDialog(null, "Registro actualizado");
                actualizar.close();
                conexion.close();}catch(NumberFormatException ex) { // handling  exception
            JOptionPane.showMessageDialog(null, "No has introducido un valor numérico en las unidades ni en el precio");
        }
    }             
    
    /* private boolean comprobarint(String variable){
	      char c = variable.charAt(0);
              
        if(Character.isLetter(c)){
          //getToolkit().beep();
                     return false;
                 }

			 else
			    return true;

	 }*/
    private void eliminaregistro() throws SQLException {
                String Base_Datos ="jdbc:mysql://localhost";
                String User = "root";
                String Contrasenna  ="12345";
                ConnectionImpl conexion = (com.mysql.cj.jdbc.ConnectionImpl) java.sql.DriverManager.getConnection(Base_Datos, User, Contrasenna );
                
                Statement eliminar = (Statement) conexion.createStatement();
                eliminar.executeUpdate("use tiendademusica;");
               // datosdetabla(jTable1);
                /*int f= jTable1.getSelectedRow();
                int c = jTable1.getSelectedColumn();
                String v=jTable1.getValueAt(f, c).toString();*/
                String busqueda = "DELETE FROM productos WHERE id_productos ="+jTable1.getValueAt(jTable1.getSelectedRow(), 0)+";";
                //int v = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
                
              //  String busqueda1 = "DELETE FROM pedidos WHERE cliente_FK ="+v+";";
              // jTable1.removeRow(f);
                //eliminar.addBatch(busqueda1);
                eliminar.addBatch(busqueda);
                eliminar.executeBatch();
                JOptionPane.showMessageDialog(null, "Registro borrado exitosamente");
                eliminar.close();
                conexion.close();
            }

}






 



  

  

